#!/bin/bash

# Set up XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME"/nixpkgs
mkdir -p "$XDG_CONFIG_HOME"/fish/completions

# Create symlinks for existing configurations
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/tmux.reset.conf" "$HOME"/tmux.reset.conf
ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix
ln -sf "$PWD/config.fish" "$XDG_CONFIG_HOME"/fish/config.fish
ln -sf "$PWD/starship.toml" "$XDG_CONFIG_HOME"/starship.toml

# Install TPM plugin for TMUX
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Fetch and set up Zsh configuration files from my main dotfiles repo

# curl -o "$HOME/.zshrc" https://raw.githubusercontent.com/mischavandenburg/dotfiles/main/.zshrc
# curl -o "$HOME/.zprofile" https://raw.githubusercontent.com/mischavandenburg/dotfiles/main/.zprofile

# Install Nix packages from config.nix
# nix-env -iA nixpkgs.myPackages

# Nix is broken due to timeouts, falling back to brew
packages=(
  fd
  bat
  asdf
  ripgrep
  npm
  lazygit
  tmux
  starship
  fzf
  kubectl
  fluxcd/tap/flux
  k9s
  kubectx
  kubens
  helm
  direnv
)

# Iterate over the array and install each package
for package in "${packages[@]}"; do
  echo "Installing $package..."
  /home/linuxbrew/.linuxbrew/bin/brew install "$package"
done

echo "All packages have been installed."

# Set up pure prompt

mkdir -p "$HOME/.zsh"
git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"

# Silence source warning

touch "$HOME/.privaterc"

# Set up completions

#midir -p "$HOME/.zfunc
flux completion fish > $XDG_CONFIG_HOME/fish/completions/flux.fish
echo -e "\nsource "(brew --prefix asdf)"/libexec/asdf.fish" >> $XDG_CONFIG_HOME/fish/config.fish
docker completion fish > $XDG_CONFIG_HOME/fish/completions/docker.fish

echo "Setup complete. Fish configuration files have been downloaded and set up."


